blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog_app import views
from blog_app import urls as blog_app_urls
from blog_app.view_jiyan import jiyan
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    #登陆验证
    url(r'^$',views.home),
    url(r'^index/$', views.home),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout),
    url(r'^check.png/$', views.check),

    #注册
    url(r'^reg/$', views.reg),
    #上传例子
    url(r'^upload/$', views.upload),

    #将个人主页的博客，分流到blog_app下的urls.py
    url(r"^blog_app/", include(blog_app_urls)),

    #富文本编辑器上传图片
    url(r'^edit_upload/', views.edit_upload),
    

    # 极验滑动验证码 获取验证码的url
    url(r'^pc-geetest/register', jiyan.get_geetest),
    url(r'^login2/$',jiyan.login2),

    #配置media路由，让头像显示在浏览器
    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT}),

    url(r'^test/$',views.test),
    



    
]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
#九张表：用户表 博客表 博客分类表 标签表 文章表 文章详情表 文章标签关系表 点赞表 评论表
class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11,null=True,unique=True)
    avatar = models.FileField(upload_to="avatars/",default="avatars/default.png",verbose_name="头像") #verbose_name 在admin中让该字段显示为 “头像”
    create_time = models.DateTimeField(auto_now_add=True)
    blog = models.OneToOneField(to="Blog",to_field="nid",null=True)

    def __str__(self):
        return self.username
    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name #默认会当做是复数，然后变成 用户s ，这里让两者相等，当复数时不加s

class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64) #博客标题
    site = models.CharField(max_length=32,unique=True) #博客后缀
    theme = models.CharField(max_length=32) #博客主题

    def __str__(self):
        return self.title

class Category(models.Model):
    """
    个人博客文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32) #标题分类
    blog = models.ForeignKey(to="Blog",to_field="nid")  #外键关联博客，一个分类可以有很多篇博客，一个博客也可以有很多个分类

    def __str__(self):
        return self.title

class Tag(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  #标签名
    blog = models.ForeignKey(to="Blog",to_field="nid")  #所属博客

    def __str__(self):
        return self.title

class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50) #文章标题
    desc = models.CharField(max_length=255) #文章描述
    # create_time = models.DateTimeField(auto_now_add=True)   #创建时间
    create_time = models.DateTimeField(auto_now_add=True)   #创建时间

    category = models.ForeignKey(to="Category",to_field="nid",null=True)
    user = models.ForeignKey(to="UserInfo",to_field="nid")
    tags = models.ManyToManyField(
        to="Tag",
        through="Article2Tag",
        through_fields=("article","tag"), #这种方式建关联表称为中介模型
    )                                       #此处第一个字段一定要填，设置多对多字段的表，也就是多对多设置在哪里第一个字段就填这张表

    #评论数
    comment_count = models.IntegerField(verbose_name="评论数", default=0)
    # 点赞数
    up_count = models.IntegerField(verbose_name="点赞数", default=0)
    # 踩
    down_count = models.IntegerField(verbose_name="踩数", default=0)

    def __str__(self):
        return self.title

class ArticleDetail(models.Model):
    """
    文章详情表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article",to_field="nid")

    def __str__(self):
        return "{}---->全文".format(self.article.title)

class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article",to_field="nid")
    tag = models.ForeignKey(to="Tag",to_field="nid")

    def __str__(self):
        return "%s----->%s标签"%(self.article.title,self.tag.title)

    class Meta:
        unique_together = (("article","tag"),)

class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo",null=True)
    article = models.ForeignKey(to="Article",null=True)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = (("article","user"),)

class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article",to_field="nid")
    user = models.ForeignKey(to="UserInfo",to_field="nid")
    content = models.CharField(max_length=255)              #评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self",null=True,blank=True)

    def __str__(self):
        return self.content

templates/2222222.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 支持手机端自动样式调整 -->
    <title>index</title>
    <link href="https://cdn.bootcss.com/normalize/8.0.0/normalize.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/fontawesome/css/font-awesome.min.css">
</head>
<body>
<div class="header">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Brand</a>
    </div>
          <ul class="nav navbar-nav">
        <li class=""><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
      </ul>
    <!-- Collect the nav links, forms, and other content for toggling -->

  </div><!-- /.container-fluid -->
</div>
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/setupajax.js"></script>
<!-- 主页面结束 -->
</body>
</html>

templates/backend_add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        * {
            margin: 0;
        }

        .header {
            width: 100%;
            height: 60px;
            background-color: #369;
        }

        .content {
            width: 80%;
            margin: 20px auto;
        }
    </style>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
     <script src="/static/jquery-3.3.1.js"></script>
</head>
<body>

<div class="header"></div>
<div class="content">
    <h3>添加文章</h3>
    <form action="/blog_app/backend/add_article/" method="post">
        {% csrf_token %}
        <div>
            <label for="">文章标题</label>
            <input type="text" name="title" class="form-control" style="width: 200px">
        </div>

        <div>
            <p>内容(TinyMCE编辑器，支持拖放/粘贴上传图片) </p>
            <textarea name="article_content" id="article_content" cols="60" rows="20"></textarea>
        </div>
        <input type="submit" class="btn btn-info">
    </form>
</div>

<script charset="utf-8" src="/static/kindeditor/kindeditor-all.js"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#article_content',{
                    width:"800",
                    height:"500px",
                    resizeType:0,           //设置是否可以自定义调整长款 有3个参数 0,1,2  2表示长款都可以自定义设置
                    uploadJson:"/edit_upload/",
                    extraFileUploadParams:{
                            csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                    },
                    filePostName:"upload_img"

                });
        });
</script>

</body>
</html>

templates/filter_show.html
{% extends "person_base.html" %}
{% block page_main %}
    <h5>该分类下的文章</h5>
    <hr>
    <div class="article_list">
        {% for article in article_list %}
            <div class="article">
                <a href="/blog_app/{{ username }}/article/{{ article.pk }}"><h3>{{ article.title }}</h3></a>
                <div class="media">
                    <div class="media-left">
                        <a href="#"><img class="media-object author-avatar" src="/media/{{ article.user.avatar }}" alt="..."></a>
                    </div>
                    <div class="media-body">
                        <p> {{ article.desc }}</p>
                    </div>
                </div>
                <div class="article-foot">
                    <span><a href="/blog_app/{{ article.user.username }}">{{ article.user.username }}</a></span>发布于
                    <span>{{ article.create_time|date:'Y-m-d H:i' }}</span>
                    {#  <span class="glyphicon glyphicon-comment"><a href="#">评论数({{ article.comment_count }})</a></span>#}
                    {#   <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.up_count }})</span>#}
                    <span><i class="fa fa-commenting-o"></i><a
                            href="#">评论数({{ article.comment_count }})</a></span>
                    <span><i class="fa fa-thumbs-o-up"></i><a class="up_count" href="#">点赞({{ article.up_count }})</a></span>
                    <hr>
                </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
{#    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 支持手机端自动样式调整 -->#}
    <title>index</title>
    <link href="https://cdn.bootcss.com/normalize/8.0.0/normalize.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/fontawesome/css/font-awesome.min.css">
</head>
<body>
<!-- 导航栏开始 -->
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

            <a class="navbar-brand" href="#">Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登陆</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!-- 导航栏结束 -->

<!-- 主页面开始 -->
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">左侧广告栏一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">左侧广告栏二</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="article_list">
                {% for article in article_list %}
                    <div class="article">
                        <a href="/blog_app/{{ article.user.username }}/article/{{ article.pk }}"><h3>{{ article.title }}</h3></a>
                        <div class="media">
                            <div class="media-left">
                                <a href="#"><img class="media-object author-avatar"
                                                 src="/media/{{ article.user.avatar }}" alt="..."></a>
                            </div>
                            <div class="media-body">
                                <p> {{ article.desc }}</p>
                            </div>
                        </div>
                        <div class="article-foot">
                            <span><a href="/blog_app/{{ article.user.username }}">{{ article.user.username }}</a></span>发布于
                            <span>{{ article.create_time|date:'Y-m-d H:i' }}</span>
                            {#                            <span class="glyphicon glyphicon-comment"><a href="#">评论数({{ article.comment_count }})</a></span>#}
                            {#                            <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.up_count }})</span>#}
                            <span><i class="fa fa-commenting-o"></i><a
                                    href="/blog_app/{{ article.user.username }}/article/{{ article.pk }}/#show_comment">评论数({{ article.comment_count }})</a></span>
                            <span><i class="fa fa-thumbs-o-up"></i><a class="up_count"
                                                                      href="#">点赞({{ article.up_count }})</a></span>
                            <hr>
                        </div>

                    </div>

                {% endfor %}
            </div>
            <nav aria-label="Page navigation p" class="text-center">
                <ul class="pagination">
                    {{ page_html|safe }}
                </ul>
            </nav>
        </div>

        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">右侧广告栏一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">右侧广告栏二</div>
                <div class="panel-body">
                    Panel content
                </div>

            </div>
        </div>
    </div>
</div>

<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/setupajax.js"></script>
<!-- 主页面结束 -->
</body>
</html>

templates/left_tag.html
<div class="panel panel-primary">
    <div class="panel-heading">文章分类</div>
    <div class="panel-body">
        {% for category in category_list %}
            <p><a href="/blog_app/{{ username }}/category/{{ category.nid }}">{{ category.title }}({{ category.article_set.count }})</a></p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-warning">
    <div class="panel-heading">标签分类</div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <p><a href="/blog_app/{{ username }}/tag/{{ tag.nid }}">{{ tag.title }}({{ tag.article_set.count }})</a></p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-info">
    <div class="panel-heading">时间分类</div>
    <div class="panel-body">
        {% for archive in archive_list %}
{#            <p><a href="/blog_app/{{ username }}/archive/{{ archive.archive_y }}/{{ archive.archive_m }}">{{ archive.archive_y }}年{{ archive.archive_m }}月({{ archive.n }})</a></p>#}
            <p><a href="/blog_app/{{ username }}/date/{{ archive.archive_y }}-{{ archive.archive_m }}">{{ archive.archive_y }}年{{ archive.archive_m }}月({{ archive.n }})</a></p>
        {% endfor %}
    </div>
</div>

templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 支持手机端自动样式调整 -->
    <title>欢迎登陆</title>
    <link href="https://cdn.bootcss.com/normalize/8.0.0/normalize.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="page-header">
                <h1>登陆</h1>
            </div>
            <form class="form-horizontal login-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">用户名</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="username" name="username" placeholder="用户名">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="password" name="password" placeholder="密码">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">验证码</label>
                    <div class="col-sm-10">
                        <input type="text" name="valid_code" id="valid_code">
                        <img id="valid-img" class="valid-img" src="/check.png" alt="验证码">
                        <p><span class="login-error"></span></p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" class="btn btn-info" id="login-button">登录</button>
                        <a class="btn btn-info" href="/reg/">注册</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/get_url_param.js"></script>
{#<script src="/static/setupajax.js"></script>#}
<script>
    $("#login-button").on("click", function () {
        var username = $("#username").val();
        var password = $("#password").val();
        var valid_code = $("#valid_code").val();
        var next_url = getUrlParam("next");
        console.log(next_url);
        $.ajax({
            url: "/login/",
            type: "post",
            data: {
                "username": username,
                "password": password,
                "valid_code": valid_code,
                "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                "next":next_url,
            },
            success: function (data) {
                if (data.status==="1") {
                    //有错误，在页面上提示
                    $(".login-error").text(data.msg);
                    $("#valid-img")[0].src += "?";
                } else if(data.status==="2"){
                    $(".login-error").text(data.msg);
                    $("#valid-img")[0].src += "?";
                }
                else {
                    //登陆成功
                    location.href = data.msg;
                }
            }
        })
    });

    //当input框获取焦点时将之前的错误清空
    $("#username,#password").focus(function () {
        $(".login-error").text("");
    });

    //点击验证码图片，刷新验证码
    $("#valid-img").click(function () {
        $(this)[0].src += "?";
    })
</script>

</body>
</html>

templates/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎登录</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>
<body>

<div class="container">
    <div class="row">
        <form class="form-horizontal col-md-6 col-md-offset-3 login-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" name="username" placeholder="用户名">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" name="password" placeholder="密码">
                </div>
            </div>
            <div class="form-group">
                <!-- 放置极验的滑动验证码 -->
                <div id="popup-captcha"></div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="button" class="btn btn-default" id="login-button">登录</button>
                    <span class="login-error"></span>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<!-- 引入封装了failback的接口--initGeetest -->
<script src="http://static.geetest.com/static/tools/gt.js"></script>
<script>

    // 极验 发送登录数据的
    var handlerPopup = function (captchaObj) {
        // 成功的回调
        captchaObj.onSuccess(function () {
            var validate = captchaObj.getValidate();
            // 1. 取到用户填写的用户名和密码 -> 取input框的值
            var username = $("#username").val();
            var password = $("#password").val();
            $.ajax({
                url: "/login/", // 进行二次验证
                type: "post",
                dataType: "json",
                data: {
                    username: username,
                    password: password,
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                    geetest_challenge: validate.geetest_challenge,
                    geetest_validate: validate.geetest_validate,
                    geetest_seccode: validate.geetest_seccode
                },
                success: function (data) {
                    console.log(data);
                    if (data.status) {
                        // 有错误，在页面上提示
                        $(".login-error").text(data.msg);
                    } else {
                        // 登陆成功
                        location.href = data.msg;
                    }
                }
            });
        });

         $("#login-button").click(function () {
            captchaObj.show();
        });
        // 将验证码加到id为captcha的元素里
        captchaObj.appendTo("#popup-captcha");
        // 更多接口参考：http://www.geetest.com/install/sections/idx-client-sdk.html
    };
    // 当input框获取焦点时将之前的错误清空
    $("#username,#password").focus(function () {
        // 将之前的错误清空
        $(".login-error").text("");
    });

    // 验证开始需要向网站主后台获取id，challenge，success（是否启用failback）
    $.ajax({
        url: "/pc-geetest/register?t=" + (new Date()).getTime(), // 加随机数防止缓存
        type: "get",
        dataType: "json",
        success: function (data) {
            // 使用initGeetest接口
            // 参数1：配置参数
            // 参数2：回调，回调的第一个参数验证码对象，之后可以使用它做appendTo之类的事件
            initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                product: "popup", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
                // 更多配置参数请参见：http://www.geetest.com/install/sections/idx-client-sdk.html#config
            }, handlerPopup);
        }
    })


</script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 支持手机端自动样式调整 -->
    <title>欢迎注册</title>
    <link href="https://cdn.bootcss.com/normalize/8.0.0/normalize.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="page-header">
                <h1>注册</h1>
            </div>

            <form action="/reg/" method="post" enctype="multipart/form-data" novalidate autocomplete="off" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.username }}
                        <span class="help-block">{{ form_obj.username.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.password }}
                        <span class="help-block">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.re_pwd.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.re_pwd.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.re_pwd }}
                        <span class="help-block">{{ form_obj.re_pwd.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.email.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.email.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.email }}
                        <span class="help-block">{{ form_obj.email.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.phone.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.phone.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.phone }}
                        <span class="help-block">{{ form_obj.phone.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label">头像</label>
                    <div class="col-sm-8">
                    <label for="id-avatar"><img id="avatar-img" src="/static/img/default.png" alt=""></label>
                    <input accept="image/*" type="file" id="id-avatar" name="avatar" style="display: none;">
                    <p class="help-block">点击图片选择</p>
                </div>
                    </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" class="btn btn-success" id="reg-submit">注册</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/setupajax.js"></script>
<script>
    //找到头像的input标签绑定change事件
    $("#id-avatar").change(function(){
        //1.创建一个读取文件的对象
        var fileReader = new FileReader();
        // 取到当前选中的头像文件
        console.log(this.files[0]);
        // 读取你选中的那个文件
        fileReader.readAsDataURL(this.files[0]); //读取文件需要时间
        fileReader.onload = function(){
            //2.等上一步读完文件之后才把图片加载到img标签中
            {#console.log(fileReader.result)#}
            $("#avatar-img").attr("src",fileReader.result);
        };
    });

    //用AJAX提交form表单、上传文件
    $("#reg-submit").click(function () {
        //观察发现 django form表单提交过来的id为： "id_"+"字段名"
        var formData = new FormData();
        formData.append("username",$("#id_username").val());
        formData.append("password",$("#id_password").val());
        formData.append("re_pwd",$("#id_re_pwd").val());
        formData.append("email",$("#id_email").val());
        formData.append("phone",$("#id_phone").val());
        formData.append("avatar",$("#id-avatar")[0].files[0]);
        formData.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val());
        $.ajax({
            url:"/reg/",
            type:"post",
            processData:false, //告诉jQuery不要去处理发送的数据
            contentType:false, //告诉jquery不要添加 content-type请求头
            data:formData,
            success:function(data){
                if (data.status){
                    //如果有错误，将错误显示在错误标签里
                    $.each(data.msg,function(k,v){
                        {#field_id = "id_"+k;#}
                        //添加input框下面紧挨着的标签内容为value，同时添加input框父标签的父标签(div)的has-error类
                        //form_boj.errors 本身打印是一个ul-li格式，传过来后变为一个字典 以 字段名：错误信息 为键值对
                        // form_obj渲染的input框 id为  id_字段名
                        $("#id_"+k).next("span").text(v[0]).parent().parent().addClass("has-error")
                    })
                }else {
                    location.href = data.msg;
                }
            }
        })
    });
    //当input框获取到焦点的时候，清除错误标签的内容
    $("form input").focus(function(){
        //把input框下面紧挨着的标签内容清空，同时删除input框父标签的父标签(div)的has-error类
        $(this).next("span").text("").parent().parent().removeClass("has-error")
    })
</script>
</body>
</html>

templates/upload.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- 支持手机端自动样式调整 -->
    <title>upload</title>
    <link href="https://cdn.bootcss.com/normalize/8.0.0/normalize.css" rel="stylesheet">
</head>
<body>
<form action="/upload/" method="post" enctype="multipart/form-data">
    <input type="file" name="file_name">
    <input type="submit" value="开始上传">
</form>
</body>
</html>